# PowerShell script to remove all TypeScript files
# This script removes all .ts and .tsx files that have JavaScript equivalents

Write-Host "=== TypeScript Files Removal Script ===" -ForegroundColor Cyan
Write-Host ""

# List of TypeScript files to remove (excluding next-env.d.ts)
$filesToRemove = @(
    # Components
    "src\app\auth\handover\page.tsx",
    "src\app\layout.tsx",
    "src\app\page.tsx",
    "src\components\common\LeaderboardItem.tsx",
    "src\components\common\LoadingScreen.tsx",
    "src\components\common\RewardAnimation.tsx",
    "src\components\common\RewardNotification.tsx",
    "src\components\common\SettingsOverlay.tsx",
    "src\components\items\BackpackItem.tsx",
    "src\components\items\ItemsOverlay.tsx",
    "src\components\leaderboard\HouseLeaderboardItem.tsx",
    "src\components\leaderboard\HouseMemberItem.tsx",
    "src\components\leaderboard\LeaderboardOverlay.tsx",
    "src\components\leaderboard\RankBadge.tsx",
    "src\components\profile\Header.tsx",
    "src\components\profile\ProfileSection.tsx",
    "src\components\quests\ImageUploadModal.tsx",
    "src\components\quests\QuestCard.tsx",
    "src\components\quests\QuestListOverlay.tsx",
    "src\components\skills\BadgeOverlay.tsx",
    "src\components\skills\SkillCard.tsx",
    
    # Hooks
    "src\hooks\useAuth.ts",
    "src\hooks\useItems.ts",
    "src\hooks\useLeaderboard.ts",
    "src\hooks\useRewardPolling.ts",
    "src\hooks\useRewards.ts",
    "src\hooks\useTheme.ts",
    "src\hooks\useUI.ts",
    
    # Handlers
    "src\handlers\profileHandlers.ts",
    "src\handlers\questHandlers.ts",
    "src\handlers\skillHandlers.ts",
    
    # Services
    "src\services\appInitialization.ts",
    "src\services\rewardService.ts",
    "src\services\socketService.ts",
    
    # Utilities
    "src\lib\api.ts",
    "src\utils\badgeSync.ts",
    "src\utils\badgeValidation.ts",
    "src\utils\countingAnimation.ts",
    "src\utils\helpers.ts",
    "src\utils\itemHelpers.ts",
    "src\utils\questHelpers.ts",
    "src\utils\rankHelpers.ts",
    "src\utils\rewardHelpers.ts",
    
    # Type Definitions
    "src\types\index.ts",
    
    # Data
    "src\data\mockQuests.ts",
    
    # Config (already converted, but remove old one if exists)
    "tailwind.config.ts"
)

$removedCount = 0
$notFoundCount = 0

Write-Host "Checking and removing TypeScript files..." -ForegroundColor Yellow
Write-Host ""

foreach ($file in $filesToRemove) {
    if (Test-Path $file) {
        Remove-Item $file -Force
        Write-Host "✓ Removed: $file" -ForegroundColor Green
        $removedCount++
    } else {
        Write-Host "✗ Not found: $file" -ForegroundColor Gray
        $notFoundCount++
    }
}

Write-Host ""
Write-Host "=== Summary ===" -ForegroundColor Cyan
Write-Host "Files removed: $removedCount" -ForegroundColor Green
Write-Host "Files not found: $notFoundCount" -ForegroundColor Gray
Write-Host ""
Write-Host "Note: next-env.d.ts was kept (auto-generated by Next.js)" -ForegroundColor Yellow
Write-Host ""
Write-Host "✅ TypeScript files removal complete!" -ForegroundColor Green
Write-Host "Your application now uses only JavaScript files." -ForegroundColor Green

